const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('assert/strict');
(async()=>{for(const file of ['ha-vacuum-water-monitor.js','custom_components/ha_vacuum_water_monitor/www/ha-vacuum-water-monitor.js']){
 const dom=new JSDOM('<html></html>',{runScripts:'dangerously',url:'http://localhost/'});
 dom.window.eval(fs.readFileSync(file,'utf8'));
 const card=dom.window.document.createElement('ha-vacuum-water-monitor');
 card._getDeviceCandidates=()=>[{vacuum_entity:'vacuum.native'},{vacuum_entity:'vacuum.matter'},{vacuum_entity:'vacuum.other'}];
 card._backendDescriptor=d=>({identity_group:d.vacuum_entity==='vacuum.other'?'separate':'same',adapter_id:d.vacuum_entity==='vacuum.matter'?'matter':'roborock'});
 card._serverState={tank_states:{'vacuum.matter':{used_ml:100}},settings:{}};
 assert.deepEqual(Array.from(card._getDevices(),d=>d.vacuum_entity),['vacuum.matter','vacuum.other']);
 card._getDevices=()=>[{vacuum_entity:'vacuum.demo'}];card._activeDeviceIdx=0;
 let calls=[];
 card._hass={callWS:async msg=>{calls.push(msg);return {settings:{custom_calibration:{keep:true}},vacuums:[{entity_id:'vacuum.demo',profile_key:'new'}]};}};
 card._render=()=>{};
 assert.equal(typeof card._reprofileDevice,'function');
 assert.equal(await card._reprofileDevice(),true);
 assert.deepEqual(calls.map(x=>x.type),['ha_vacuum_water_monitor/reprofile']);
 assert.equal(card._discoveredVacuums[0].profile_key,'new');
 card._hass.callWS=async()=>{throw new Error('offline');};
 assert.equal(await card._reprofileDevice(),false);
 card.shadowRoot.innerHTML='<select id="cal-cycle"><option value="0" data-cycle-ts="100">Cycle</option></select><input id="cal-observed"><input id="cal-resolution"><div id="cal-export-status"></div><textarea id="cal-export-preview" hidden></textarea><button id="cal-download" disabled></button>';
 const preview=card.shadowRoot.getElementById('cal-export-preview');
 const download=card.shadowRoot.getElementById('cal-download');
 card._hass.callWS=async msg=>{calls.push(msg);return {kind:'contribution_draft',runtime_eligible:false};};
 assert.equal(await card._previewCalibration({vacuum_entity:'vacuum.demo'}),true);
 assert.equal(calls.at(-1).session_ts,100);
 assert.equal(calls.at(-1).type,'ha_vacuum_water_monitor/calibration_preview');
 assert.equal(download.disabled,false);
 assert.equal(JSON.parse(preview.value).runtime_eligible,false);
 card.shadowRoot.getElementById('cal-observed').value='100';
 assert.equal(await card._previewCalibration({vacuum_entity:'vacuum.demo'}),false);
 assert.equal(download.disabled,true);
 card.shadowRoot.getElementById('cal-resolution').value='5';
 card._hass.callWS=async()=>{throw new Error('offline');};
 assert.equal(await card._previewCalibration({vacuum_entity:'vacuum.demo'}),false);
 assert.equal(download.disabled,true);
 assert.equal(preview.hidden,true);
 let resolveDraft;
 card._hass.callWS=()=>new Promise(resolve=>{resolveDraft=resolve;});
 const pending=card._previewCalibration({vacuum_entity:'vacuum.demo'});
 card._calibrationPreviewGeneration++;
 resolveDraft({kind:'stale'});
 assert.equal(await pending,false);
 assert.equal(download.disabled,true);
 card._serverState={settings:{},tank_states:{'vacuum.demo':{automatic_sessions:{invalid:true}}}};
 assert.equal(card._getSessionsFromStorage({vacuum_entity:'vacuum.demo'}).length,0);
 assert.doesNotThrow(()=>card._buildHistoryTab({vacuum_entity:'vacuum.demo'},{}));
 card.shadowRoot.innerHTML='<select id="cal-cycle"><option value="0" data-cycle-ts="100">Cycle</option></select><input id="cal-observed" value="100"><input id="cal-resolution" value="5"><select id="cal-instrument"><option value="graduated_jug">Jug</option></select><select id="cal-purpose"><option value="training">Training</option></select><input id="cal-boundaries" type="checkbox"><input id="cal-uninterrupted" type="checkbox"><button id="cal-save"></button><div id="cal-local-status"></div>';
 calls=[];
 card._hass.callWS=async msg=>{calls.push(msg);return {saved:true,sample_count:1,calibration:null};};
 assert.equal(typeof card._saveLocalMeasurement,'function');
 assert.equal(await card._saveLocalMeasurement({vacuum_entity:'vacuum.demo'}),false);
 assert.equal(calls.length,0);
 card.shadowRoot.getElementById('cal-boundaries').checked=true;
 card.shadowRoot.getElementById('cal-uninterrupted').checked=true;
 assert.equal(await card._saveLocalMeasurement({vacuum_entity:'vacuum.demo'}),true);
 assert.equal(calls[0].type,'ha_vacuum_water_monitor/save_measurement');
 assert.equal(calls[0].session_ts,100);
 assert.equal(calls[0].measurement.observed_ml,100);
 assert.match(card.shadowRoot.getElementById('cal-local-status').textContent,/1/);
 card._hass.callWS=async()=>{throw new Error('offline');};
 assert.equal(await card._saveLocalMeasurement({vacuum_entity:'vacuum.demo'}),false);
 assert.match(card.shadowRoot.getElementById('cal-local-status').textContent,/Could not/);
 const diagnostics=card._buildDiagnostics({consumptionResolution:{source:'verified_model',profile_id:'<script>x</script>',method:'area',dataset_version:'v1',validation:{max_error_ml:5}}});
 assert.match(diagnostics,/v1/);assert.match(diagnostics,/5/);assert(!diagnostics.includes('<script>'));
 card._serverState={settings:{sessions:{'vacuum.demo':[null]}},tank_states:{'vacuum.demo':{automatic_sessions:[null,{},'bad']}}};
 assert.doesNotThrow(()=>card._buildHistoryTab({vacuum_entity:'vacuum.demo'},{}));
 assert.equal(card._getSessionsFromStorage({vacuum_entity:'vacuum.demo'}).length,0);
 const readiness=card._measurementReadiness({area:10,exposure_complete:true,segments:1,context:null});
 assert.match(readiness,/historical context/i);
 const levelDiagnostics=card._buildDiagnostics({reservoirLevels:{dock_clean:{volume_ml:3900},dock_dirty:{volume_ml:null,reason:'volume_sensor_unbound'}}});
 assert.match(levelDiagnostics,/3900|3,900/);assert.match(levelDiagnostics,/dock_dirty/);
 card.shadowRoot.innerHTML='<select id="cal-cycle"><option value="0" data-cycle-ts="100">Cycle</option></select><input id="cal-observed" value="100"><input id="cal-resolution" value="5"><select id="cal-instrument"><option value="graduated_jug">Jug</option></select><select id="cal-purpose"><option value="training">Training</option></select><input id="cal-boundaries" type="checkbox" checked><input id="cal-uninterrupted" type="checkbox" checked><button id="cal-save"></button><div id="cal-local-status"></div>';
 card._hass.callWS=async()=>({});
 assert.equal(await card._saveLocalMeasurement({vacuum_entity:'vacuum.demo'}),false);
 let resolveMeasurement;
 card._hass.callWS=()=>new Promise(resolve=>{resolveMeasurement=resolve;});
 const pendingMeasurement=card._saveLocalMeasurement({vacuum_entity:'vacuum.demo'});
 card._localMeasurementGeneration=(card._localMeasurementGeneration||0)+1;
 card.shadowRoot.getElementById('cal-local-status').textContent='Selected another cycle';
 resolveMeasurement({saved:true,sample_count:3,calibration:{}});
 await pendingMeasurement;
 assert.equal(card.shadowRoot.getElementById('cal-local-status').textContent,'Selected another cycle');
 card._hass={states:{'vacuum.demo':{state:'docked',attributes:{}}}};
 card._serverState={settings:{},tank_states:{'vacuum.demo':{initialized:true,used_ml:0,accounting_v2:{status:'unknown',reason:'stale_event_stream'}}}};
 card._withBackendDescriptor=d=>d; card._backendDescriptor=()=>null;
 const v2Data=card._calcDeviceData({vacuum_entity:'vacuum.demo',accounting_event_sensor:'sensor.events',tracked_reservoir:'dock_clean',tracked_capacity_ml:4000});
 assert.equal(v2Data.percentRemaining,null);
 assert.equal(v2Data.stateReason,'stale_event_stream');
 const streamDiag=card._buildDiagnostics({accountingV2:{status:'known',source_contract_id:'reviewed',balances_ml:{dock_clean:1260},external_supply_ml:300,external_drain_ml:80}});
 assert.ok(streamDiag.includes('Physical transfer balance'));
 assert.ok(streamDiag.includes('External supply'));
 const staleDiag=card._buildDiagnostics({accountingV2:{status:'unknown',reason:'stale_event_stream',balances_ml:{dock_clean:9999}}});
 assert.ok(staleDiag.includes('stale_event_stream'));
 assert.ok(!staleDiag.includes('9999'));
 card._serverState={settings:{},tank_states:{'vacuum.demo':{initialized:true,used_ml:0,accounting_incomplete:true}}};
 card._withBackendDescriptor=d=>d; card._backendDescriptor=()=>null; card._explicitDeviceKeys=()=>new Set(['water_total_ml']);
 const incomplete=card._calcDeviceData({vacuum_entity:'vacuum.demo',water_total_ml:4000,config_provenance:{authored_fields:['water_total_ml']}});
 assert.equal(incomplete.percentRemaining,null);
 assert.equal(incomplete.usedMl,null);
 assert.equal(incomplete.stateReason,'accounting_incomplete');
 dom.window.close();
} console.log('Sprint UI: reprofile and contribution preview/failure/stale-response PASS, both copies');})().catch(e=>{console.error(e);process.exit(1);});
